<?php require dirname(__DIR__) . '/config/app-version.php'; ?>
<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Usuário · MetaFit Admin</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
  <link href="/assets/css/style.css?v=0.1.3" rel="stylesheet">
</head>
<body class="app-page">
  <aside class="sidebar"><a class="brand" href="/users">MetaFit</a><nav class="sidebar-nav"><a class="active" href="/users"><i class="bi bi-people"></i> Usuários</a></nav><div class="sidebar-bottom"></div></aside>
  <main class="main-content">
    <header class="page-header">
      <div><a class="text-decoration-none small text-muted" href="/users"><i class="bi bi-arrow-left me-1"></i>Usuários</a><h1 id="page-title" class="mt-2">Novo usuário</h1><p id="page-description" class="text-muted mb-0">Cadastre uma pessoa para acessar a plataforma.</p></div>
    </header>
    <div id="page-alert" class="alert alert-danger d-none" role="alert"></div>
    <form id="user-page-form" novalidate>
      <div class="row g-4">
        <section class="col-12"><div class="content-card">
          <h5 class="mb-4">Informações pessoais</h5>
          <div class="row g-3">
            <div class="col-md-7"><label class="form-label" for="user-nome">Nome completo</label><input class="form-control" id="user-nome" required></div>
            <div class="col-md-5"><label class="form-label" for="user-nome-preferido">Nome preferido</label><input class="form-control" id="user-nome-preferido"></div>
            <div class="col-md-7"><label class="form-label" for="user-email">E-mail</label><input class="form-control" type="email" id="user-email" required></div>
            <div class="col-md-5"><label class="form-label" for="user-whatsapp">WhatsApp</label><input class="form-control" id="user-whatsapp" required placeholder="(00) 00000-0000"><small id="whatsapp-edit-note" class="form-text d-none">A alteração do WhatsApp seguirá um protocolo específico.</small></div>
            <div class="col-md-6"><label class="form-label" for="user-data-nascimento">Data de nascimento</label><input class="form-control" type="date" id="user-data-nascimento"></div>
            <div class="col-md-6"><label class="form-label" for="user-sexo">Sexo</label><select class="form-select" id="user-sexo"><option value="nao_informado">Não informado</option><option value="feminino">Feminino</option><option value="masculino">Masculino</option><option value="outro">Outro</option></select></div>
            <div class="col-12"><label class="form-label" for="user-instrucoes-ia">Preferências e instruções de atendimento</label><textarea class="form-control" id="user-instrucoes-ia" rows="4" maxlength="2000" placeholder="Ex.: Prefere mensagens curtas. Evitar falar sobre calorias."></textarea><small class="form-text">Orientações privadas para personalizar a comunicação da IA. Não substituem regras de saúde e segurança.</small></div>
          </div>
        </div></section>
        <section id="account-details" class="col-12 d-none"><div class="content-card"><h5 class="mb-4">Detalhes do registro</h5><div class="row g-3 small">
          <div class="col-md-3"><span class="text-muted d-block">Situação</span><strong id="detail-situacao">—</strong></div><div class="col-md-3"><span class="text-muted d-block">Última mensagem no WhatsApp</span><strong id="detail-whatsapp">—</strong></div><div class="col-md-3"><span class="text-muted d-block">Último login</span><strong id="detail-login">—</strong></div><div class="col-md-3"><span class="text-muted d-block">Criado em</span><strong id="detail-created">—</strong></div>
          <div class="col-md-3"><span class="text-muted d-block">Cadastro inicial</span><strong id="detail-onboarding">—</strong></div><div class="col-md-3"></div><div class="col-md-3"><span class="text-muted d-block">Canal WhatsApp</span><strong id="detail-channel">—</strong></div><div class="col-md-3"><span class="text-muted d-block">Vigência do acesso</span><strong id="detail-access-duration">—</strong></div>
        </div></div></section>
        <section id="account-history-section" class="col-12 d-none"><div class="content-card"><h5 class="mb-3">Histórico da conta</h5><div id="account-history-list"></div></div></section>
        <section id="invoices-section" class="col-12 d-none"><div class="content-card"><div class="d-flex justify-content-between align-items-center mb-4"><h5 class="mb-0">Faturas</h5><span id="invoices-summary" class="small text-muted"></span></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Emissão</th><th>Valor</th><th>Crédito</th><th>Situação</th><th>Pagamento</th><th></th></tr></thead><tbody id="invoices-list"></tbody></table></div><hr class="my-4"><h6 class="mb-3">Lançar fatura manual</h6><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label" for="invoice-amount">Valor (R$)</label><input id="invoice-amount" class="form-control" type="number" min="0" step="0.01" value="0.00"></div><div class="col-md-2"><label class="form-label" for="invoice-credit-days">Dias de crédito</label><input id="invoice-credit-days" class="form-control" type="number" min="0" step="1" value="30"></div><div class="col-md-3"><label class="form-label" for="invoice-payment-method">Forma de pagamento</label><select id="invoice-payment-method" class="form-select"><option value="pix">PIX</option><option value="bonificacao">Bonificação</option><option value="dinheiro">Dinheiro</option><option value="transferencia">Transferência</option><option value="cartao">Cartão</option><option value="outro">Outro</option></select></div><div class="col-md-2"><label class="form-label" for="invoice-status">Situação</label><select id="invoice-status" class="form-select"><option value="paga">Paga</option><option value="pendente">Pendente</option></select></div><div class="col-md-2"><button id="create-invoice" type="button" class="btn btn-primary w-100">Lançar fatura</button></div></div></div></section>
      </div>
      <div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-light" href="/users">Cancelar</a><button id="user-submit" class="btn btn-primary" type="submit">Cadastrar usuário</button></div>
    </form>
  </main>
  <div class="modal fade" id="manual-invoice-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="manual-invoice-form"><div class="modal-header"><div><p class="eyebrow mb-1">LANÇAMENTO MANUAL</p><h5 class="modal-title">Nova fatura</h5></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="manual-invoice-amount">Valor (R$)</label><input id="manual-invoice-amount" class="form-control" type="number" min="0" step="0.01" value="0.00" required></div><div class="col-md-6"><label class="form-label" for="manual-invoice-credit-days">Dias de crédito</label><input id="manual-invoice-credit-days" class="form-control" type="number" min="0" step="1" value="30" required></div><div class="col-12"><label class="form-label" for="manual-invoice-status">Situação</label><select id="manual-invoice-status" class="form-select" style="appearance:auto"><option value="paga">Paga</option><option value="pendente">Pendente</option></select></div><div class="col-12"><label class="form-label" for="manual-invoice-payment-method">Forma de pagamento</label><select id="manual-invoice-payment-method" class="form-select" style="appearance:auto"><option value="pix">PIX</option><option value="bonificacao">Bonificação</option><option value="dinheiro">Dinheiro</option><option value="transferencia">Transferência</option><option value="cartao">Cartão</option><option value="outro">Outro</option></select></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button><button id="manual-invoice-submit" class="btn btn-primary" type="submit">Lançar fatura</button></div></form></div></div></div>
  <div class="modal fade" id="invoice-history-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><p class="eyebrow mb-1">HISTÓRICO DA FATURA</p><h5 class="modal-title">Registros e observações</h5></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div id="invoice-history-list" class="modal-body"></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Fechar</button></div></div></div></div>
  <div class="modal fade" id="reverse-payment-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="reverse-payment-form"><div class="modal-header"><div><p class="eyebrow mb-1">ESTORNO</p><h5 class="modal-title">Estornar pagamento</h5></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label" for="reverse-invoice-status">Novo status</label><select id="reverse-invoice-status" class="form-select" style="appearance:auto"><option value="pendente">Pendente</option><option value="cancelada">Cancelada</option></select></div><div class="col-12"><label class="form-label" for="reverse-payment-reason">Motivo do estorno</label><textarea id="reverse-payment-reason" class="form-control" rows="4" required placeholder="Ex.: pagamento devolvido pelo banco."></textarea><small class="form-text">O motivo será registrado no histórico da fatura.</small></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button><button id="reverse-payment-submit" class="btn btn-danger" type="submit">Confirmar estorno</button></div></form></div></div></div>
  <div class="modal fade" id="pix-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><p class="eyebrow mb-1">COBRANÇA PIX</p><h5 class="modal-title">PIX copia e cola</h5></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><textarea id="pix-copy-paste-code" class="form-control" rows="8" readonly></textarea></div><div class="modal-footer"><button id="copy-pix-code" type="button" class="btn btn-primary"><i class="bi bi-copy me-1"></i>Copiar</button></div></div></div></div>
  <div class="modal fade" id="confirm-payment-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="confirm-payment-form"><div class="modal-header"><div><p class="eyebrow mb-1">CONFIRMAÇÃO MANUAL</p><h5 class="modal-title">Confirmar pagamento</h5></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="confirm-invoice-amount">Valor da fatura (R$)</label><input id="confirm-invoice-amount" class="form-control" type="number" min="0" step="0.01" required></div><div class="col-md-6"><label class="form-label" for="confirm-credit-days">Dias de crédito</label><input id="confirm-credit-days" class="form-control" type="number" min="0" step="1" required></div><div class="col-12"><label class="form-label" for="confirm-paid-at">Data e hora do pagamento</label><input id="confirm-paid-at" class="form-control" type="datetime-local" required></div><div class="col-12"><label class="form-label" for="confirm-payment-method">Forma de pagamento</label><select id="confirm-payment-method" class="form-select" style="appearance:auto"><option value="pix">PIX</option><option value="dinheiro">Dinheiro</option><option value="transferencia">Transferência</option><option value="cartao">Cartão</option><option value="bonificacao">Bonificação</option><option value="outro">Outro</option></select></div><div class="col-12"><label class="form-label" for="confirm-payment-note">Observações</label><textarea id="confirm-payment-note" class="form-control" rows="3" placeholder="Ex.: comprovante recebido pelo WhatsApp."></textarea></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button><button id="confirm-payment-submit" class="btn btn-primary" type="submit">Confirmar pagamento</button></div></form></div></div></div>
  <footer class="system-footer server-footer">&copy; Todos os direitos reservados a <a href="https://rocketprodutora.com.br" target="_blank" rel="noopener">Rocket Produtora Digital</a> · <span class="system-version">v<?= htmlspecialchars($metaFitAdminVersion, ENT_QUOTES, 'UTF-8') ?></span></footer>
  <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="/assets/js/config.js?v=0.1.4"></script><script src="/assets/js/api.js?v=0.1.2"></script><script src="/assets/js/user-page.js"></script>
</body>
</html>
